name: Build ChiX Editor and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.py --onefile --noconsole --name ChiX --icon=generated-icon.png

      - name: Get short commit hash
        id: vars
        shell: pwsh
        run: |
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          echo "SHORT_SHA=$shortSha" >> $env:GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "ChiX Editor Build ${{ env.SHORT_SHA }}"
          draft: false
          prerelease: false
          files: dist/ChiX.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}